"""empty message

Revision ID: 929955c661de
Revises: 
Create Date: 2018-03-14 17:31:01.089594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929955c661de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('path', sa.Unicode(length=128), nullable=True))
    op.drop_column('question', 'picture_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('picture_url', sa.VARCHAR(length=80), nullable=True))
    op.drop_column('question', 'path')
    # ### end Alembic commands ###
